var JSON5="object"===typeof exports?exports:{};
JSON5.parse=function(){var k,b,g,a,f={"'":"'",'"':'"',"\\":"\\","/":"/","\n":"",b:"\b",f:"\f",n:"\n",r:"\r",t:"\t"},c=" \t\r\n\x0B\f\u00a0\ufeff".split(""),h,u=function(a){return""===a?"EOF":"'"+a+"'"},e=function(a){var p=new SyntaxError;p.message=a+" at line "+b+" column "+g+" of the JSON5 data. Still to read: "+JSON.stringify(h.substring(k-1,k+19));p.at=k;p.lineNumber=b;p.columnNumber=g;throw p;},d=function(E){E&&E!==a&&e("Expected "+u(E)+" instead of "+u(a));a=h.charAt(k);k++;g++;if("\n"===a||
"\r"===a&&"\n"!==h.charAt(k))b++,g=0;return a},l=function(){var b,p="";b="";var c=10;if("-"===a||"+"===a)p=a,d(a);if("I"===a)return b=v(),("number"!==typeof b||isNaN(b))&&e("Unexpected word for number"),"-"===p?-b:b;if("N"===a)return b=v(),isNaN(b)||e("expected word to be NaN"),b;"0"===a&&(b+=a,d(),"x"===a||"X"===a?(b+=a,d(),c=16):"0"<=a&&"9">=a&&e("Octal literal"));switch(c){case 10:for(;"0"<=a&&"9">=a;)b+=a,d();if("."===a)for(b+=".";d()&&"0"<=a&&"9">=a;)b+=a;if("e"===a||"E"===a){b+=a;d();if("-"===
a||"+"===a)b+=a,d();for(;"0"<=a&&"9">=a;)b+=a,d()}break;case 16:for(;"0"<=a&&"9">=a||"A"<=a&&"F">=a||"a"<=a&&"f">=a;)b+=a,d()}b="-"===p?-b:+b;if(isFinite(b))return b;e("Bad number")},n=function(){var b,c,x="",l,n;if('"'===a||"'"===a)for(l=a;d();){if(a===l)return d(),x;if("\\"===a)if(d(),"u"===a){for(c=n=0;4>c;c+=1){b=parseInt(d(),16);if(!isFinite(b))break;n=16*n+b}x+=String.fromCharCode(n)}else if("\r"===a)"\n"===h.charAt(k)&&d();else if("string"===typeof f[a])x+=f[a];else break;else if("\n"===a)break;
else x+=a}e("Bad string")},q=function(){for(;a;)if("/"===a)if("/"!==a&&e("Not a comment"),d("/"),"/"===a){"/"!==a&&e("Not an inline comment");do if(d(),"\n"===a||"\r"===a){d();break}while(a)}else if("*"===a)a:{"*"!==a&&e("Not a block comment");do for(d();"*"===a;)if(d("*"),"/"===a){d("/");break a}while(a);e("Unterminated block comment")}else e("Unrecognized comment");else if(0<=c.indexOf(a))d();else break},v=function(){switch(a){case "t":return d("t"),d("r"),d("u"),d("e"),!0;case "f":return d("f"),
d("a"),d("l"),d("s"),d("e"),!1;case "n":return d("n"),d("u"),d("l"),d("l"),null;case "I":return d("I"),d("n"),d("f"),d("i"),d("n"),d("i"),d("t"),d("y"),Infinity;case "N":return d("N"),d("a"),d("N"),NaN}e("Unexpected "+u(a))},x;x=function(){q();switch(a){case "{":var b;a:{var c;b={};if("{"===a)for(d("{"),q();a;){if("}"===a){d("}");break a}if('"'===a||"'"===a)c=n();else for(c=a,"_"!==a&&"$"!==a&&("a">a||"z"<a)&&("A">a||"Z"<a)&&e("Bad identifier as unquoted key");d()&&("_"===a||"$"===a||"a"<=a&&"z">=
a||"A"<=a&&"Z">=a||"0"<=a&&"9">=a);)c+=a;q();d(":");b[c]=x();q();if(","!==a){d("}");break a}d(",");q()}e("Bad object");b=void 0}return b;case "[":a:{b=[];if("["===a)for(d("["),q();a;){if("]"===a){d("]");break a}","===a?e("Missing array element"):b.push(x());q();if(","!==a){d("]");break a}d(",");q()}e("Bad array");b=void 0}return b;case '"':case "'":return n();case "-":case "+":case ".":return l();default:return"0"<=a&&"9">=a?l():v()}};return function(c,p){var d;h=String(c);k=0;g=b=1;a=" ";d=x();q();
a&&e("Syntax error");return"function"===typeof p?function K(b,a){var c,x,d=b[a];if(d&&"object"===typeof d)for(c in d)Object.prototype.hasOwnProperty.call(d,c)&&(x=K(d,c),void 0!==x?d[c]=x:delete d[c]);return p.call(b,a,d)}({"":d},""):d}}();
JSON5.stringify=function(k,b,g){function a(b){if("string"!==typeof b)return!1;var a=b[0];if(!("a"<=a&&"z">=a||"A"<=a&&"Z">=a||"_"===a||"$"===a))return!1;for(var a=1,c=b.length;a<c;){var d=b[a];if(!("a"<=d&&"z">=d||"A"<=d&&"Z">=d||"0"<=d&&"9">=d||"_"===d||"$"===d))return!1;a++}return!0}function f(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)}function c(a){for(var b=0;b<l.length;b++)if(l[b]===a)throw new TypeError("Converting circular structure to JSON");
}function h(a,b,c){if(!a)return"";10<a.length&&(a=a.substring(0,10));c=c?"":"\n";for(var d=0;d<b;d++)c+=a;return c}function u(a){q.lastIndex=0;return q.test(a)?'"'+a.replace(q,function(a){var b=v[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function e(b,q,p){(p=d(b,q,p))&&"[object Date]"!==Object.prototype.toString.call(p)&&(p=p.valueOf());switch(typeof p){case "boolean":return p.toString();case "number":return isNaN(p)||!isFinite(p)?"null":
p.toString();case "string":return u(p.toString());case "object":if(null===p)return"null";if(f(p)){c(p);b="[";l.push(p);for(var g=0;g<p.length;g++)q=e(p,g,!1),b+=h(n,l.length),b=null===q||"undefined"===typeof q?b+"null":b+q,g<p.length-1?b+=",":n&&(b+="\n");l.pop();b+=h(n,l.length,!0)+"]"}else{c(p);b="{";var k=!1;l.push(p);for(g in p)if(p.hasOwnProperty(g)){var v=e(p,g,!1);"undefined"!==typeof v&&null!==v&&(b+=h(n,l.length),k=!0,q=a(g)?g:u(g),b+=q+":"+(n?" ":"")+v+",")}l.pop();b=k?b.substring(0,b.length-
1)+h(n,l.length)+"}":"{}"}return b}}if(b&&"function"!==typeof b&&!f(b))throw Error("Replacer must be a function or an array");var d=function(a,c,d){var n=a[c];n&&n.toJSON&&"function"===typeof n.toJSON&&(n=n.toJSON());if("function"===typeof b)return b.call(a,c,n);if(b){if(d||f(a)||0<=b.indexOf(c))return n}else return n};JSON5.isWord=a;var l=[],n;g&&("string"===typeof g?n=g:"number"===typeof g&&0<=g&&(n=h(" ",g,!0)));var q=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
v={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};g={"":k};return void 0===k?d(g,"",!0):e(g,"",!0)};"object"!==typeof JSON&&(JSON={});
(function(){function k(a){return 10>a?"0"+a:a}function b(){return this.valueOf()}function g(a){e.lastIndex=0;return e.test(a)?'"'+a.replace(e,function(a){var b=q[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function a(b,c){var d,f,q,h,e=l,k,r=c[b];r&&"object"===typeof r&&"function"===typeof r.toJSON&&(r=r.toJSON(b));"function"===typeof v&&(r=v.call(c,b,r));switch(typeof r){case "string":return g(r);case "number":return isFinite(r)?String(r):
"null";case "boolean":case "null":return String(r);case "object":if(!r)return"null";l+=n;k=[];if("[object Array]"===Object.prototype.toString.apply(r)){h=r.length;for(d=0;d<h;d+=1)k[d]=a(d,r)||"null";q=0===k.length?"[]":l?"[\n"+l+k.join(",\n"+l)+"\n"+e+"]":"["+k.join(",")+"]";l=e;return q}if(v&&"object"===typeof v)for(h=v.length,d=0;d<h;d+=1)"string"===typeof v[d]&&(f=v[d],(q=a(f,r))&&k.push(g(f)+(l?": ":":")+q));else for(f in r)Object.prototype.hasOwnProperty.call(r,f)&&(q=a(f,r))&&k.push(g(f)+(l?
": ":":")+q);q=0===k.length?"{}":l?"{\n"+l+k.join(",\n"+l)+"\n"+e+"}":"{"+k.join(",")+"}";l=e;return q}}var f=/^[\],:{}\s]*$/,c=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,h=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,u=/(?:^|:|,)(?:\s*\[)+/g,e=/[\\\"\u0000-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,d=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;
"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+k(this.getUTCMonth()+1)+"-"+k(this.getUTCDate())+"T"+k(this.getUTCHours())+":"+k(this.getUTCMinutes())+":"+k(this.getUTCSeconds())+"Z":null},Boolean.prototype.toJSON=b,Number.prototype.toJSON=b,String.prototype.toJSON=b);var l,n,q,v;"function"!==typeof JSON.stringify&&(q={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},JSON.stringify=
function(b,c,d){var f;n=l="";if("number"===typeof d)for(f=0;f<d;f+=1)n+=" ";else"string"===typeof d&&(n=d);if((v=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("JSON.stringify");return a("",{"":b})});"function"!==typeof JSON.parse&&(JSON.parse=function(a,b){function n(a,c){var d,l,f=a[c];if(f&&"object"===typeof f)for(d in f)Object.prototype.hasOwnProperty.call(f,d)&&(l=n(f,d),void 0!==l?f[d]=l:delete f[d]);return b.call(a,c,f)}var l;a=String(a);d.lastIndex=
0;d.test(a)&&(a=a.replace(d,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(f.test(a.replace(c,"@").replace(h,"]").replace(u,"")))return l=eval("("+a+")"),"function"===typeof b?n({"":l},""):l;throw new SyntaxError("JSON.parse");})})();(function(){function k(a,b){function c(a){if(c[a]!==z)return c[a];var t;if("bug-string-char-index"==a)t=!1;else if("json"==a)t=c("json-stringify")&&c("json-parse");else{var f;if("json-stringify"==a){t=b.stringify;var l="function"==typeof t&&A;if(l){(f=function(){return 1}).toJSON=f;try{l="0"===t(0)&&"0"===t(new d)&&'""'==t(new h)&&t(y)===z&&t(z)===z&&t()===z&&"1"===t(f)&&"[1]"==t([f])&&"[null]"==t([z])&&"null"==t(null)&&"[null,null,null]"==t([z,y,null])&&'{"a":[1,true,false,null,"\\u0000\\b\\n\\f\\r\\t"]}'==
t({a:[f,!0,!1,null,"\x00\b\n\f\r\t"]})&&"1"===t(null,f)&&"[\n 1,\n 2\n]"==t([1,2],null,1)&&'"-271821-04-20T00:00:00.000Z"'==t(new p(-864E13))&&'"+275760-09-13T00:00:00.000Z"'==t(new p(864E13))&&'"-000001-01-01T00:00:00.000Z"'==t(new p(-621987552E5))&&'"1969-12-31T23:59:59.999Z"'==t(new p(-1))}catch(g){l=!1}}t=l}if("json-parse"==a){t=b.parse;if("function"==typeof t)try{if(0===t("0")&&!t(!1)){f=t('{"a":[1,true,false,null,"\\u0000\\b\\n\\f\\r\\t"]}');var e=5==f.a.length&&1===f.a[0];if(e){try{e=!t('"\t"')}catch(g){}if(e)try{e=
1!==t("01")}catch(g){}if(e)try{e=1!==t("1.")}catch(g){}}}}catch(g){e=!1}t=e}}return c[a]=!!t}a||(a=f.Object());b||(b=f.Object());var d=a.Number||f.Number,h=a.String||f.String,e=a.Object||f.Object,p=a.Date||f.Date,u=a.SyntaxError||f.SyntaxError,R=a.TypeError||f.TypeError,K=a.Math||f.Math,G=a.JSON||f.JSON;"object"==typeof G&&G&&(b.stringify=G.stringify,b.parse=G.parse);var e=e.prototype,y=e.toString,r,F,z,A=new p(-0xc782b5b800cec);try{A=-109252==A.getUTCFullYear()&&0===A.getUTCMonth()&&1===A.getUTCDate()&&
10==A.getUTCHours()&&37==A.getUTCMinutes()&&6==A.getUTCSeconds()&&708==A.getUTCMilliseconds()}catch(L){}if(!c("json")){var H=c("bug-string-char-index");if(!A)var B=K.floor,S=[0,31,59,90,120,151,181,212,243,273,304,334],I=function(a,b){return S[b]+365*(a-1970)+B((a-1969+(b=+(1<b)))/4)-B((a-1901+b)/100)+B((a-1601+b)/400)};(r=e.hasOwnProperty)||(r=function(a){var b={},c;(b.__proto__=null,b.__proto__={toString:1},b).toString!=y?r=function(a){var b=this.__proto__;a=a in(this.__proto__=null,this);this.__proto__=
b;return a}:(c=b.constructor,r=function(a){var b=(this.constructor||c).prototype;return a in this&&!(a in b&&this[a]===b[a])});b=null;return r.call(this,a)});F=function(a,b){var c=0,d,f,n;(d=function(){this.valueOf=0}).prototype.valueOf=0;f=new d;for(n in f)r.call(f,n)&&c++;d=f=null;c?F=2==c?function(a,b){var c={},d="[object Function]"==y.call(a),f;for(f in a)d&&"prototype"==f||r.call(c,f)||!(c[f]=1)||!r.call(a,f)||b(f)}:function(a,b){var c="[object Function]"==y.call(a),d,f;for(d in a)c&&"prototype"==
d||!r.call(a,d)||(f="constructor"===d)||b(d);(f||r.call(a,d="constructor"))&&b(d)}:(f="valueOf toString toLocaleString propertyIsEnumerable isPrototypeOf hasOwnProperty constructor".split(" "),F=function(a,b){var c="[object Function]"==y.call(a),d,L=!c&&"function"!=typeof a.constructor&&g[typeof a.hasOwnProperty]&&a.hasOwnProperty||r;for(d in a)c&&"prototype"==d||!L.call(a,d)||b(d);for(c=f.length;d=f[--c];L.call(a,d)&&b(d));});return F(a,b)};if(!c("json-stringify")){var T={92:"\\\\",34:'\\"',8:"\\b",
12:"\\f",10:"\\n",13:"\\r",9:"\\t"},C=function(a,b){return("000000"+(b||0)).slice(-a)},O=function(a){for(var b='"',c=0,d=a.length,f=!H||10<d,n=f&&(H?a.split(""):a);c<d;c++){var l=a.charCodeAt(c);switch(l){case 8:case 9:case 10:case 12:case 13:case 34:case 92:b+=T[l];break;default:b=32>l?b+("\\u00"+C(2,l.toString(16))):b+(f?n[c]:a.charAt(c))}}return b+'"'},M=function(a,b,c,d,f,n,l){var g,e,q,h,m,k,p,v,u;try{g=b[a]}catch(G){}if("object"==typeof g&&g)if(e=y.call(g),"[object Date]"!=e||r.call(g,"toJSON"))"function"==
typeof g.toJSON&&("[object Number]"!=e&&"[object String]"!=e&&"[object Array]"!=e||r.call(g,"toJSON"))&&(g=g.toJSON(a));else if(g>-1/0&&g<1/0){if(I){h=B(g/864E5);for(e=B(h/365.2425)+1970-1;I(e+1,0)<=h;e++);for(q=B((h-I(e,0))/30.42);I(e,q+1)<=h;q++);h=1+h-I(e,q);m=(g%864E5+864E5)%864E5;k=B(m/36E5)%24;p=B(m/6E4)%60;v=B(m/1E3)%60;m%=1E3}else e=g.getUTCFullYear(),q=g.getUTCMonth(),h=g.getUTCDate(),k=g.getUTCHours(),p=g.getUTCMinutes(),v=g.getUTCSeconds(),m=g.getUTCMilliseconds();g=(0>=e||1E4<=e?(0>e?
"-":"+")+C(6,0>e?-e:e):C(4,e))+"-"+C(2,q+1)+"-"+C(2,h)+"T"+C(2,k)+":"+C(2,p)+":"+C(2,v)+"."+C(3,m)+"Z"}else g=null;c&&(g=c.call(b,a,g));if(null===g)return"null";e=y.call(g);if("[object Boolean]"==e)return""+g;if("[object Number]"==e)return g>-1/0&&g<1/0?""+g:"null";if("[object String]"==e)return O(""+g);if("object"==typeof g){for(a=l.length;a--;)if(l[a]===g)throw R();l.push(g);u=[];b=n;n+=f;if("[object Array]"==e){q=0;for(a=g.length;q<a;q++)e=M(q,g,c,d,f,n,l),u.push(e===z?"null":e);a=u.length?f?"[\n"+
n+u.join(",\n"+n)+"\n"+b+"]":"["+u.join(",")+"]":"[]"}else F(d||g,function(a){var b=M(a,g,c,d,f,n,l);b!==z&&u.push(O(a)+":"+(f?" ":"")+b)}),a=u.length?f?"{\n"+n+u.join(",\n"+n)+"\n"+b+"}":"{"+u.join(",")+"}":"{}";l.pop();return a}};b.stringify=function(a,b,c){var d,f,n,e;if(g[typeof b]&&b)if("[object Function]"==(e=y.call(b)))f=b;else if("[object Array]"==e){n={};for(var l=0,q=b.length,h;l<q;h=b[l++],(e=y.call(h),"[object String]"==e||"[object Number]"==e)&&(n[h]=1));}if(c)if("[object Number]"==(e=
y.call(c))){if(0<(c-=c%1))for(d="",10<c&&(c=10);d.length<c;d+=" ");}else"[object String]"==e&&(d=10>=c.length?c:c.slice(0,10));return M("",(h={},h[""]=a,h),f,n,d,"",[])}}if(!c("json-parse")){var U=h.fromCharCode,V={92:"\\",34:'"',47:"/",98:"\b",116:"\t",110:"\n",102:"\f",114:"\r"},m,J,w=function(){m=J=null;throw u();},D=function(){for(var a=J,b=a.length,c,d,f,g,e;m<b;)switch(e=a.charCodeAt(m),e){case 9:case 10:case 13:case 32:m++;break;case 123:case 125:case 91:case 93:case 58:case 44:return c=H?
a.charAt(m):a[m],m++,c;case 34:c="@";for(m++;m<b;)if(e=a.charCodeAt(m),32>e)w();else if(92==e)switch(e=a.charCodeAt(++m),e){case 92:case 34:case 47:case 98:case 116:case 110:case 102:case 114:c+=V[e];m++;break;case 117:d=++m;for(f=m+4;m<f;m++)e=a.charCodeAt(m),48<=e&&57>=e||97<=e&&102>=e||65<=e&&70>=e||w();c+=U("0x"+a.slice(d,m));break;default:w()}else{if(34==e)break;e=a.charCodeAt(m);for(d=m;32<=e&&92!=e&&34!=e;)e=a.charCodeAt(++m);c+=a.slice(d,m)}if(34==a.charCodeAt(m))return m++,c;w();default:d=
m;45==e&&(g=!0,e=a.charCodeAt(++m));if(48<=e&&57>=e){for(48==e&&(e=a.charCodeAt(m+1),48<=e&&57>=e)&&w();m<b&&(e=a.charCodeAt(m),48<=e&&57>=e);m++);if(46==a.charCodeAt(m)){for(f=++m;f<b&&(e=a.charCodeAt(f),48<=e&&57>=e);f++);f==m&&w();m=f}e=a.charCodeAt(m);if(101==e||69==e){e=a.charCodeAt(++m);43!=e&&45!=e||m++;for(f=m;f<b&&(e=a.charCodeAt(f),48<=e&&57>=e);f++);f==m&&w();m=f}return+a.slice(d,m)}g&&w();if("true"==a.slice(m,m+4))return m+=4,!0;if("false"==a.slice(m,m+5))return m+=5,!1;if("null"==a.slice(m,
m+4))return m+=4,null;w()}return"$"},N=function(a){var b,c;"$"==a&&w();if("string"==typeof a){if("@"==(H?a.charAt(0):a[0]))return a.slice(1);if("["==a){for(b=[];;c||(c=!0)){a=D();if("]"==a)break;c&&(","==a?(a=D(),"]"==a&&w()):w());","==a&&w();b.push(N(a))}return b}if("{"==a){for(b={};;c||(c=!0)){a=D();if("}"==a)break;c&&(","==a?(a=D(),"}"==a&&w()):w());","!=a&&"string"==typeof a&&"@"==(H?a.charAt(0):a[0])&&":"==D()||w();b[a.slice(1)]=N(D())}return b}w()}return a},Q=function(a,b,c){c=P(a,b,c);c===
z?delete a[b]:a[b]=c},P=function(a,b,c){var d=a[b],e;if("object"==typeof d&&d)if("[object Array]"==y.call(d))for(e=d.length;e--;)Q(d,e,c);else F(d,function(a){Q(d,a,c)});return c.call(a,b,d)};b.parse=function(a,b){var c,d;m=0;J=""+a;c=N(D());"$"!=D()&&w();m=J=null;return b&&"[object Function]"==y.call(b)?P((d={},d[""]=c,d),"",b):c}}}b.runInContext=k;return b}var b="function"===typeof define&&define.amd,g={"function":!0,object:!0},a=g[typeof exports]&&exports&&!exports.nodeType&&exports,f=g[typeof window]&&
window||this,c=a&&g[typeof module]&&module&&!module.nodeType&&"object"==typeof global&&global;!c||c.global!==c&&c.window!==c&&c.self!==c||(f=c);if(a&&!b)k(f,a);else{var h=f.JSON,u=f.JSON3,e=!1,d=k(f,f.JSON3={noConflict:function(){e||(e=!0,f.JSON=h,f.JSON3=u,h=u=null);return d}});f.JSON={parse:d.parse,stringify:d.stringify}}b&&define(function(){return d})}).call(this);"function"!==typeof JSON.decycle&&null==JSON.decycle&&(JSON.decycle=function(k,b){var g=[],a=[];return function c(h,k){var e,d;void 0!==b&&(h=b(h));if(!("object"!==typeof h||null===h||h instanceof Boolean||h instanceof Date||h instanceof Number||h instanceof RegExp||h instanceof String)){e=g.indexOf(h);if(0<=e)return{$ref:a[e]};g.push(h);a.push(k);Array.isArray(h)?(d=[],h.forEach(function(a,b){d[b]=c(a,k+"["+b+"]")})):(d={},Object.keys(h).forEach(function(a){d[a]=c(h[a],k+"["+JSON.stringify(a)+"]")}));
return d}return h}(k,"$")});
"function"!==typeof JSON.retrocycle&&null==JSON.retrocycle&&(JSON.retrocycle=function(k){var b=/^\$(?:\[(?:\d+|\"(?:[^\\\"\u0000-\u001f]|\\([\\\"\/bfnrt]|u[0-9a-zA-Z]{4}))*\")\])*$/;(function a(f){f&&"object"===typeof f&&(Array.isArray(f)?f.forEach(function(c,h){if("object"===typeof c&&null!==c){var k=c.$ref;"string"===typeof k&&b.test(k)?f[h]=eval(k):a(c)}}):Object.keys(f).forEach(function(c){var h=f[c];if("object"===typeof h&&null!==h){var k=h.$ref;"string"===typeof k&&b.test(k)?f[c]=eval(k):a(h)}}))})(k);
return k});JSON.download=function(k,b){var g="text/json;charset=utf-8,"+encodeURIComponent(JSON.stringify(k));if(null==b||""==b)b="savefile.json";var a=document.createElement("a");a.href="data:"+g;a.download=-1!=b.indexOf(".json")||-1!=b.indexOf(".txt")?b:b+".json";a.click();document.body.appendChild(a)};
JSON.parse_recursive=function(){function k(a){return a.replace(/\\(?:u(.{4})|([^u]))/g,function(a,b,c){return b?String.fromCharCode(parseInt(b,16)):h[c]})}var b,g,a,f,c,h={"\\":"\\",'"':'"',"/":"/",t:"\t",n:"\n",r:"\r",f:"\f",b:"\b"},u={go:function(){b="ok"},firstokey:function(){f=c;b="colon"},okey:function(){f=c;b="colon"},ovalue:function(){b="ocomma"},firstavalue:function(){b="acomma"},avalue:function(){b="acomma"}},e={go:function(){b="ok"},ovalue:function(){b="ocomma"},firstavalue:function(){b=
"acomma"},avalue:function(){b="acomma"}},d={"{":{go:function(){g.push({state:"ok"});a={};b="firstokey"},ovalue:function(){g.push({container:a,state:"ocomma",key:f});a={};b="firstokey"},firstavalue:function(){g.push({container:a,state:"acomma"});a={};b="firstokey"},avalue:function(){g.push({container:a,state:"acomma"});a={};b="firstokey"}},"}":{firstokey:function(){var d=g.pop();c=a;a=d.container;f=d.key;b=d.state},ocomma:function(){var d=g.pop();a[f]=c;c=a;a=d.container;f=d.key;b=d.state}},"[":{go:function(){g.push({state:"ok"});
a=[];b="firstavalue"},ovalue:function(){g.push({container:a,state:"ocomma",key:f});a=[];b="firstavalue"},firstavalue:function(){g.push({container:a,state:"acomma"});a=[];b="firstavalue"},avalue:function(){g.push({container:a,state:"acomma"});a=[];b="firstavalue"}},"]":{firstavalue:function(){var d=g.pop();c=a;a=d.container;f=d.key;b=d.state},acomma:function(){var d=g.pop();a.push(c);c=a;a=d.container;f=d.key;b=d.state}},":":{colon:function(){if(Object.hasOwnProperty.call(a,f))throw new SyntaxError("Duplicate key '"+
f+'"');b="ovalue"}},",":{ocomma:function(){a[f]=c;b="okey"},acomma:function(){a.push(c);b="avalue"}},"true":{go:function(){c=!0;b="ok"},ovalue:function(){c=!0;b="ocomma"},firstavalue:function(){c=!0;b="acomma"},avalue:function(){c=!0;b="acomma"}},"false":{go:function(){c=!1;b="ok"},ovalue:function(){c=!1;b="ocomma"},firstavalue:function(){c=!1;b="acomma"},avalue:function(){c=!1;b="acomma"}},"null":{go:function(){c=null;b="ok"},ovalue:function(){c=null;b="ocomma"},firstavalue:function(){c=null;b="acomma"},
avalue:function(){c=null;b="acomma"}}};return function(a,f){var h,v=/^[\u0020\t\n\r]*(?:([,:\[\]{}]|true|false|null)|(-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)|"((?:[^\r\n\t\\\"]|\\(?:["\\\/trnfb]|u[0-9a-fA-F]{4}))*)")/;b="go";g=[];try{for(;;){h=v.exec(a);if(!h)break;if(h[1])d[h[1]][b]();else h[2]?(c=+h[2],e[b]()):(c=k(h[3]),u[b]());a=a.slice(h[0].length)}}catch(x){b=x}if("ok"!==b||/[^\u0020\t\n\r]/.test(a))throw b instanceof SyntaxError?b:new SyntaxError("JSON");return"function"===typeof f?function E(a,
b){var d,e,g=a[b];if(g&&"object"===typeof g)for(d in c)Object.prototype.hasOwnProperty.call(g,d)&&(e=E(g,d),void 0!==e?g[d]=e:delete g[d]);return f.call(a,b,g)}({"":c},""):c}}();
JSON.parse_state=function(){var k,b,g={'"':'"',"\\":"\\","/":"/",b:"\b",f:"\f",n:"\n",r:"\r",t:"\t"},a,f=function(b){throw{name:"SyntaxError",message:b,at:k,text:a};},c=function(c){c&&c!==b&&f("Expected '"+c+"' instead of '"+b+"'");b=a.charAt(k);k+=1;return b},h=function(){var a;a="";"-"===b&&(a="-",c("-"));for(;"0"<=b&&"9">=b;)a+=b,c();if("."===b)for(a+=".";c()&&"0"<=b&&"9">=b;)a+=b;if("e"===b||"E"===b){a+=b;c();if("-"===b||"+"===b)a+=b,c();for(;"0"<=b&&"9">=b;)a+=b,c()}a=+a;if(isFinite(a))return a;
f("Bad number")},u=function(){var a,d,e="",h;if('"'===b)for(;c();){if('"'===b)return c(),e;if("\\"===b)if(c(),"u"===b){for(d=h=0;4>d;d+=1){a=parseInt(c(),16);if(!isFinite(a))break;h=16*h+a}e+=String.fromCharCode(h)}else if("string"===typeof g[b])e+=g[b];else break;else e+=b}f("Bad string")},e=function(){for(;b&&" ">=b;)c()},d=function(){switch(b){case "t":return c("t"),c("r"),c("u"),c("e"),!0;case "f":return c("f"),c("a"),c("l"),c("s"),c("e"),!1;case "n":return c("n"),c("u"),c("l"),c("l"),null}f("Unexpected '"+
b+"'")},l;l=function(){e();switch(b){case "{":var a;a:{var g={};if("{"===b){c("{");e();if("}"===b){c("}");a=g;break a}for(;b;){a=u();e();c(":");Object.hasOwnProperty.call(g,a)&&f("Duplicate key '"+a+"'");g[a]=l();e();if("}"===b){c("}");a=g;break a}c(",");e()}}f("Bad object");a=void 0}return a;case "[":a:{a=[];if("["===b){c("[");e();if("]"===b){c("]");break a}for(;b;){a.push(l());e();if("]"===b){c("]");break a}c(",");e()}}f("Bad array");a=void 0}return a;case '"':return u();case "-":return h();default:return"0"<=
b&&"9">=b?h():d()}};return function(c,d){var g;a=c;k=0;b=" ";g=l();e();b&&f("Syntax error");return"function"===typeof d?function E(a,b){var c,e,f=a[b];if(f&&"object"===typeof f)for(c in f)Object.prototype.hasOwnProperty.call(f,c)&&(e=E(f,c),void 0!==e?f[c]=e:delete f[c]);return d.call(a,b,f)}({"":g},""):g}}();