(function(a,d){function b(a){m[p]=c.apply(d,a);return p++}function c(a){var b=[].slice.call(arguments,1);return function(){"function"===typeof a?a.apply(d,b):(new Function(""+a))()}}function f(a){if(n)setTimeout(c(f,a),0);else{var b=m[a];if(b){n=!0;try{b()}finally{e(a),n=!1}}}}function e(a){delete m[a]}function g(){h=function(){var a=b(arguments);process.nextTick(c(f,a));return a}}function q(){if(a.postMessage&&!a.importScripts){var b=!0,c=a.onmessage;a.onmessage=function(){b=!1};a.postMessage("",
"*");a.onmessage=c;return b}}function r(){var c="setImmediate$"+Math.random()+"$",e=function(b){b.source===a&&"string"===typeof b.data&&0===b.data.indexOf(c)&&f(+b.data.slice(c.length))};a.addEventListener?a.addEventListener("message",e,!1):a.attachEvent("onmessage",e);h=function(){var e=b(arguments);a.postMessage(c+e,"*");return e}}function t(){var a=new MessageChannel;a.port1.onmessage=function(a){f(a.data)};h=function(){var c=b(arguments);a.port2.postMessage(c);return c}}function u(){var a=l.documentElement;
h=function(){var c=b(arguments),e=l.createElement("script");e.onreadystatechange=function(){f(c);e.onreadystatechange=null;a.removeChild(e);e=null};a.appendChild(e);return c}}function v(){h=function(){var a=b(arguments);setTimeout(c(f,a),0);return a}}if(!a.setImmediate){var p=1,m={},n=!1,l=a.document,h,k=Object.getPrototypeOf&&Object.getPrototypeOf(a),k=k&&k.setTimeout?k:a;"[object process]"==={}.toString.call(a.process)?g():q()?r():a.MessageChannel?t():l&&"onreadystatechange"in l.createElement("script")?
u():v();k.setImmediate=h;k.clearImmediate=e}})("undefined"===typeof self?"undefined"===typeof global?this:global:self);var performanceNow=performance.now||performance.mozNow||performance.msNow||performance.oNow||performance.webkitNow||function(){return(new Date).getTime()},hrtime=function(a){var d=.001*performanceNow.call(performance),b=Math.floor(d),d=Math.floor(d%1*1E9);a&&(b-=a[0],d-=a[1],0>d&&(b--,d+=1E9));return[b,d]};
function NanoTimer(a){this.timeOutT1=this.intervalT1=null;this.intervalCount=1;this.deferredTimeout=this.deferredInterval=!1;this.intervalImmediateRef=this.timeoutImmediateRef=this.intervalCallbackRef=this.timeoutCallbackRef=this.deferredIntervalRef=this.deferredTimeoutRef=null;this.intervalErrorChecked=!1;this.intervalType="";this.timeoutTriggered=!1;a&&(this.logging=!0)}
NanoTimer.prototype.time=function(a,d,b,c){if(c){var f=hrtime();d?(d.push(function(){var a=hrtime(f);"s"==b?c(a[0]+a[1]/1E9):"m"==b?c(1E3*a[0]+a[1]/1E6):"u"==b?c(1E6*a[0]+a[1]/1E3):"n"==b?c(1E9*a[0]+a[1]):c(a)}),a.apply(null,d)):a(function(){var a=hrtime(f);"s"==b?c(a[0]+a[1]/1E9):"m"==b?c(1E3*a[0]+a[1]/1E6):"u"==b?c(1E6*a[0]+a[1]/1E3):"n"==b?c(1E9*a[0]+a[1]):c(a)})}else return f=hrtime(),d?a.apply(null,d):a(),a=hrtime(f),"s"==b?a[0]+a[1]/1E9:"m"==b?1E3*a[0]+a[1]/1E6:"u"==b?1E6*a[0]+a[1]/1E3:"n"==
b?1E9*a[0]+a[1]:hrtime(f)};
NanoTimer.prototype.setInterval=function(a,d,b,c){this.intervalErrorChecked||(a?"function"!=typeof a&&console.log("Task argument to setInterval must be a function reference"):console.log("A task function must be specified to setInterval"),b?"string"!=typeof b&&console.log("Interval argument to setInterval must be a string specified as an integer followed by 's' for seconds, 'm' for milli, 'u' for micro, and 'n' for nanoseconds. Ex. 2u"):console.log("An interval argument must be specified"),c&&("function"!=
typeof c?console.log("Callback argument to setInterval must be a function reference"):this.intervalCallbackRef=c),this.intervalType=b[b.length-1],"s"==this.intervalType?this.intervalTime=1E9*b.slice(0,b.length-1):"m"==this.intervalType?this.intervalTime=1E6*b.slice(0,b.length-1):"u"==this.intervalType?this.intervalTime=1E3*b.slice(0,b.length-1):"n"==this.intervalType?this.intervalTime=b.slice(0,b.length-1):console.log("Error with argument: "+b+': Incorrect interval format. Format is an integer followed by "s" for seconds, "m" for milli, "u" for micro, and "n" for nanoseconds. Ex. 2u'),
this.intervalErrorChecked=!0);var f=this;0<this.intervalTime?(null==this.intervalT1&&(this.intervalT1=hrtime()),8E15<this.intervalTime*this.intervalCount&&(this.intervalT1=hrtime(),this.intervalCount=1),this.difArray=hrtime(this.intervalT1),this.difTime=1E9*this.difArray[0]+this.difArray[1],this.difTime<this.intervalTime*this.intervalCount?25E6<this.intervalTime?0==this.deferredInterval?(this.deferredInterval=!0,this.deferredIntervalRef=setTimeout(function(){f.setInterval(a,d,b,c)},(this.intervalTime-
25E6)/1E6)):(this.deferredIntervalRef=null,this.intervalImmediateRef=setImmediate(function(){f.setInterval(a,d,b,c)})):this.intervalImmediateRef=setImmediate(function(){f.setInterval(a,d,b,c)}):(this.intervalImmediateRef=null,this.logging&&console.log("nanotimer log: cycle time at - "+this.difTime),d?a.apply(null,d):a(),this.intervalT1&&(this.intervalCount++,this.deferredInterval=!1,this.intervalImmediateRef=setImmediate(function(){f.setInterval(a,d,b,c)})))):(null==this.intervalT1&&(this.intervalT1=
hrtime()),d?a.apply(null,d):a(),this.intervalT1&&(this.intervalImmediateRef=setImmediate(function(){f.setInterval(a,d,b,c)})))};
NanoTimer.prototype.setTimeout=function(a,d,b,c){a?"function"!=typeof a&&console.log("Task argument to setTimeout must be a function reference"):console.log("A task function must be specified to setTimeout");b?"string"!=typeof b&&console.log("Delay argument to setTimeout must be a string specified as an integer followed by 's' for seconds, 'm' for milli, 'u' for micro, and 'n' for nanoseconds. Ex. 2u"):console.log("A delay argument must be specified");c&&("function"!=typeof c?console.log("Callback argument to setTimeout must be a function reference"):
this.timeoutCallbackRef=c);var f=this;this.timeoutTriggered&&(this.timeoutTriggered=!1);var e=b[b.length-1];if("s"==e)var g=1E9*b.slice(0,b.length-1);else"m"==e?g=1E6*b.slice(0,b.length-1):"u"==e?g=1E3*b.slice(0,b.length-1):"n"==e?g=b.slice(0,b.length-1):console.log("Error with argument: "+b+': Incorrect delay format. Format is an integer followed by "s" for seconds, "m" for milli, "u" for micro, and "n" for nanoseconds. Ex. 2u');null==this.timeOutT1&&(this.timeOutT1=hrtime());e=hrtime(this.timeOutT1);
e=1E9*e[0]+e[1];e<g?25E6<g?0==this.deferredTimeout?(this.deferredTimeout=!0,this.deferredTimeoutRef=setTimeout(function(){f.setTimeout(a,d,b,c)},(g-25E6)/1E6)):(this.deferredTimeoutRef=null,this.timeoutImmediateRef=setImmediate(function(){f.setTimeout(a,d,b,c)})):this.timeoutImmediateRef=setImmediate(function(){f.setTimeout(a,d,b,c)}):(this.timeoutTriggered=!0,this.timeOutT1=this.timeoutImmediateRef=null,this.deferredTimeout=!1,1==this.logging&&console.log("nanotimer log: actual wait - "+e),d?a.apply(null,
d):a(),c&&c({waitTime:e}))};NanoTimer.prototype.clearInterval=function(){this.deferredIntervalRef&&(clearTimeout(this.deferredIntervalRef),this.deferredInterval=!1);this.intervalImmediateRef&&clearImmediate(this.intervalImmediateRef);this.intervalT1=null;this.intervalCount=1;this.intervalErrorChecked=!1;this.intervalCallbackRef&&this.intervalCallbackRef()};
NanoTimer.prototype.clearTimeout=function(){if(0==this.timeoutTriggered){if(this.deferredTimeoutRef){clearTimeout(this.deferredTimeoutRef);if(this.timeOutT1)var a=hrtime(this.timeOutT1),a=1E9*a[0]+a[1];this.deferredTimeout=!1}this.timeoutImmediateRef&&clearImmediate(this.timeoutImmediateRef);this.timeOutT1=null;this.timeoutCallbackRef&&this.timeoutCallbackRef({waitTime:a})}};